export let majors = [
    {id: 1, name: 'Építészmérnöki (BSc)'},
    {id: 2, name: 'Építőmérnöki (BSc)'},
    {id: 3, name: 'Építőművészet (BA)'},
    {id: 4, name: 'Gépészmérnöki (BSc)'},
    {id: 5, name: 'Ipari termék- és formatervező mérnöki (BSc)'},
    {id: 6, name: 'Környezetmérnöki (BSc)'},
    {id: 7, name: 'Mérnökinformatikus (BSc)'},
    {id: 8, name: 'Villamosmérnöki (BSc)'},
    {id: 9, name: 'Belsőépítész tervezőművész (MA)'},
    {id: 10, name: 'Egészségügyi mérnök (MSc)'},
    {id: 11, name: 'Építész (MSc)'},
    {id: 12, name: 'Építőművész (MA)'},
    {id: 13, name: 'Gépészmérnöki (MSc)'},
    {id: 14, name: 'Mérnökinformatikus (MSc)'},
    {id: 15, name: 'Szerkezet-építőmérnöki (MSc)'},
    {id: 16, name: 'Településmérnöki (MSc)'},
    {id: 17, name: 'Breuer Marcell Doktori Iskola'},
    {id: 18, name: 'Műszaki felsőoktatási szakképzés (FOKSZ)'},
    {id: 19, name: 'Televíziós műsorkészítő (FOKSZ)'},
    {id: 20, name: 'Építészmérnöki osztatlan'},
    {id: 21, name: 'BIM szakmérnök'},
    {id: 22, name: 'Atomerőművi üzemeltetési szakember'},
    {id: 23, name: 'Atomerőművi üzemeltetési szakmérnök'},
    {id: 24, name: 'Hulladékgazdálkodási szakmérnök / műszaki szakember'},
    {id: 25, name: 'Létesítmény-energetikai szakmérnök'},
    {id: 26, name: 'Minőségirányítási rendszermenedzser'},
    {id: 27, name: 'Nukleáris környezetvédelmi szakmérnök / szakember'},
    {id: 28, name: 'Történeti épületdiagnosztikai és rehabilitációs szakmérnök / szakember'},
    {id: 29, name: 'Városüzemeltető szakmérnök'},
    {id: 30, name: 'Vizuális mediátor, iskolai designer'},
    {id: 31, name: 'Zaj- és rezgésvédelmi szakmérnök / szakember'}
];